// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqllQDo5MEx8Ke9-9wQubxHDLlbkyqSp0',
    appId: '1:826505912571:web:7c538af32504928192505e',
    messagingSenderId: '826505912571',
    projectId: 'chit-chat-809f5',
    authDomain: 'chit-chat-809f5.firebaseapp.com',
    storageBucket: 'chit-chat-809f5.appspot.com',
    measurementId: 'G-JPXXQM50RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNtQUXBDdOq8YENeIkDZsqLlFNElUoUb8',
    appId: '1:826505912571:android:9aa199bfe696024f92505e',
    messagingSenderId: '826505912571',
    projectId: 'chit-chat-809f5',
    storageBucket: 'chit-chat-809f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcwDh3LmXLS8bEqlfBECyQ-auH5odpv4U',
    appId: '1:826505912571:ios:c040d6b5158d0fe692505e',
    messagingSenderId: '826505912571',
    projectId: 'chit-chat-809f5',
    storageBucket: 'chit-chat-809f5.appspot.com',
    iosClientId: '826505912571-3b3l4bu8uq67i62pml9ckbqs21f2oami.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcwDh3LmXLS8bEqlfBECyQ-auH5odpv4U',
    appId: '1:826505912571:ios:c040d6b5158d0fe692505e',
    messagingSenderId: '826505912571',
    projectId: 'chit-chat-809f5',
    storageBucket: 'chit-chat-809f5.appspot.com',
    iosClientId: '826505912571-3b3l4bu8uq67i62pml9ckbqs21f2oami.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat',
  );
}
